### ISSUE TITLE
mkdir .minetest/textures

### ISSUE THREAD

**Issue by ghost** [sofar/mcresconvert#14]
Hi,
If their is no textures folder, it fails to convert.

thanks for the script !

**Comment by sofar** [comment]
If this folder is missing then your minetest isn't properly installed, and we don't want to automatically create this folder.

**Comment by wilkgr76** [comment]
Perhaps this should have a better name, e.g. "Fails to convert if textures folder is missing", perhaps...
@GwendalDurdik

**Comment by sofar** [comment]
The title is fine, perhaps an error message is needed in the code.

**Comment by wilkgr76** [comment]
@sofar Fine...

**Comment by ensonic** [comment]
I've send a PR for this. The **local** texture folder is not part of the minetest install if you never installed a texture pack.
