### ISSUE TITLE
half doors from the start trek ressource pack

### ISSUE THREAD

**Issue by ensonic** [sofar/mcresconvert#16]
http://www.planetminecraft.com/texture_pack/chrisryots-star-trek-textures/

The converted doors only fill the upper half. Do we need to remap sections of the texture?

![doors_door_wood](https://cloud.githubusercontent.com/assets/1279486/16707478/76d4df82-45cf-11e6-8a6f-71c53eef2d4c.png)

**Comment by ensonic** [comment]
The issue sees to be that the converter assumes that all images follow the same base size (or some defined ratio).

```
file blocks/cobblestone.png
blocks/cobblestone.png: PNG image data, 256 x 256, 8-bit/color RGB, non-interlaced
file blocks/door_wood_upper.png 
blocks/door_wood_upper.png: PNG image data, 128 x 128, 8-bit/color RGB, non-interlaced
```

**Comment by sofar** [comment]
Determining aspect ratio for each texture is possible, but complex because many textures are in a map or don't follow simple multiplier rules. That's of course a texture pack design error. I'm not so sure I feel like fixing this, since it's a corner case and most texture packs don't do this.

**Comment by ensonic** [comment]
Is there a reference for what the 'simple multiplier rules' should be? For now I'll probably fix up the source files and rerun the conversion.
Would be nice if we could warn such files, but I guess we could also fix them in that case.

**Comment by sofar** [comment]
Right now, everything is determined as a multiplier of the cobblestone texture ($PX). Doors are therefore expected to be PX x 2PX (w x h) etc..
