### ISSUE TITLE
script errors

### ISSUE THREAD

**Issue by githubgnulinux** [sofar/mcresconvert#19]
Command terminal output below:

./mcresconvert.sh 
Automatically converting resourcepacks and texturepacks found...
Scanning for texture/resourcepacks...
find: `~/.minecraft/texturepacks/': No such file or directory
find:`~/.minecraft/resourcepacks': No such file or directory

Programmers should consider this scenario of not having minecraft installed, only minetest; as a result, created these directories and repeated the script.

./mcresconvert.sh 
Automatically converting resourcepacks and texturepacks found...
Scanning for texture/resourcepacks...
Found: minetestzipfile
- File: minetestzipfile.zip
  mkdir: cannot create directory ‘~/.minetest/textures/minetestzipfile/minetestzipfile’: No such file or directory
  mkdir: cannot create directory ‘~/.minetest/textures/minetestzipfile/_z’: No such file or directory
  checkdir:  cannot create extraction directory: ~/.minetest/textures/minetestzipfile/minetestzipfile/_z
         No such file or directory
  ./mcresconvert.sh: line 57: cd: ~/.minetest/textures/minetestzipfile/minetestzipfile/_z: No such file or directory
  chmod: changing permissions of [privatefilename]: Operation not permitted
  chmod: changing permissions of [privatefilename]: Operation not permitted
  ./mcresconvert.sh: line 257: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 257: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 257: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 257: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 257: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 257: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 257: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 257: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 257: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 257: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 257: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 257: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 257: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 257: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 257: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 257: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 257: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 257: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 257: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 257: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 257: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 257: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 257: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 257: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 257: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 257: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 257: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 257: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 257: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 257: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 257: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 257: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 257: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 257: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 257: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 257: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 257: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 257: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 257: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 257: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 257: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 257: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 257: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 257: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 257: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 257: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 257: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 257: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 257: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 257: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 257: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 257: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 257: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 257: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 257: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 257: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 257: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 257: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 257: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 257: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 257: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 257: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 257: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 257: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 257: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 257: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 257: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 257: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 257: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 257: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 257: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 257: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 257: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 257: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 257: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 257: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 257: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 257: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 257: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 257: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 257: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 257: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 257: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 257: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 257: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 257: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 257: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 257: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 257: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 257: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 257: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 257: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 257: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 257: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 257: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 257: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 257: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 257: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 257: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 257: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 257: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 257: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 257: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 257: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 257: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 257: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 257: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 257: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 257: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 257: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 257: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 257: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 257: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 257: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 257: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 257: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 257: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 257: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 257: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 257: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 257: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 257: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 257: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 257: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 257: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 257: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 257: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 257: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 257: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 257: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 257: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 257: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 257: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 257: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 257: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 257: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 257: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 257: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 257: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 257: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 257: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 257: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 257: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 257: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 257: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 257: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 257: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 257: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 257: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 257: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 257: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 257: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 257: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 257: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 257: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 257: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 257: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 257: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 257: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 257: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 257: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 257: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 257: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 257: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 257: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 257: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 257: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 257: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 257: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 257: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 257: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 257: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 257: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 257: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 257: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 257: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 257: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 257: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 257: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 257: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 257: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 257: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 257: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 257: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 271: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 339: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 353: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 365: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 383: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 433: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 450: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 459: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 470: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 477: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 487: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 495: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 504: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 512: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 533: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 540: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 548: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 555: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 571: _n/_tot: No such file or directory
  find: `_z': No such file or directory
  cat: _n/_counter: No such file or directory
  cat: _n/_tot: No such file or directory
  ./mcresconvert.sh: line 586: 100 \* count / tot: division by 0 (error token is "tot")

Where '[privatefilename]' is shown, this corresponds to the names of randomly selected files also in the same directory as the shell script. Why should the script change permissions of these files?

This script was repeated in a new empty directory cotaining only the script file. The error  referring to '_n/_tot/' continues.

**Comment by sofar** [comment]
Seems like a bogus test file. Please use an actual minetest texture pack zip file and pick one that we can also test - IOW show where you downloaded it from.
