### ISSUE TITLE
If Minetest is not in default place

### ISSUE THREAD

**Issue by amadin** [sofar/mcresconvert#21]
I downloaded pirate version of Minecraft 1.8.8 and this script can't find textures to convert. Path is
/mnt/sda3/Minecraft_1.8.8/versions/1.8.8/1.8.9.jar. If extract .jar file then "textures" folder will contain:

```
$ dir
blocks    effect  environment  gui    map   models    particle
colormap  entity  font         items  misc  painting
```

Minetest also not in default place.
I solved my problem by downloading .jar file from pirate Minecraft server site, run it and then choose "/home/ra/.minecraftonly/Classic/resourcepacks/Minecraft default.zip" but converted textures was created in .minetest folder in home directory but my Minetest not here, it was compiled with -DRUN_IN_PLACE=TRUE

**Comment by sofar** [comment]
Impossible to solve non-standard or hacked installs, and I'm not inclined to even try.
