### ISSUE TITLE
Replace Mese Lamp texture with glow stone texture

### ISSUE THREAD

**Issue by masrourmouad** [sofar/mcresconvert#22]
Replace Mese Lamp texture with glow stone texture, thanks

**Comment by sofar** [comment]
Make a patch. It's not that hard.

**Comment by masrourmouad** [comment]
![patch](https://cloud.githubusercontent.com/assets/403487/19912558/2849b896-a093-11e6-8e4a-00e83fb07d3b.png)
thanks for the response, i made a patch , for chests do you have any clues how to make it.

**Comment by sofar** [comment]
Where's the pull request?
