### ISSUE TITLE
Some blocks are missed with texture pack 

### ISSUE THREAD

**Issue by amadin** [sofar/mcresconvert#25]
Trouble only with one texture pack. Some textures are missed (default_grass.png, default_grass_1.png etc., default_leaves.png etc.). It don't have "Colormap" directory. I downloaded different versions of this texture pack and from different sites, everywhere the same trouble. Is this because it don't have "Colormap" directory?
I can't upload zip file for unknown reason, file Minecraft Enhanced 1.8 [64x].zip here [LINK TO COPYRIGHT VIOLATION REMOVED]

**Comment by masrourmouad** [comment]
i repair it for you.
[Minecraft Enhanced 1.8 [64x].zip](https://github.com/minetest-tools/mcresconvert/files/583742/Minecraft.Enhanced.1.8.64x.zip)

**Comment by amadin** [comment]
Thank you.

**Comment by sofar** [comment]
You shouldn't upload copyrighted material. I've removed the file and link URL.

**Comment by sofar** [comment]
You should make a patch for mcresconvert, don't be stupid and violate copyright law by distributing copyrighted material without permission. That's just going to get this project in trouble.
