### ISSUE TITLE
Skyboxes

### ISSUE THREAD

**Issue by tacotexmex** [sofar/mcresconvert#27]
Some texture packs, like Pixel Perfection, have skyboxes included. Is there a way to support them?

**Comment by sofar** [comment]
Yes, but modifying skyboxes requires that a `mod` adds them.

We could import them into the texture pack, but there's no way for the player to see them unless some lua code (on the **server**) actually enables them.

So, right now we consider it out of scope, since it can't be themed client-side.

**Comment by tacotexmex** [comment]
Thanks for considering the issue. May I ask if such server mod exist, or do I have to make one?

**Comment by sofar** [comment]
I have not seen any specific mod that does this. I've heard of some subgames doing this, but don't recall names. It's not that difficult, though, just check the lua_api.txt to see the sky functions.
