### ISSUE TITLE
White or transperent vertical edges on cactus (some packs only)

### ISSUE THREAD

**Issue by Fixer-007** [sofar/mcresconvert#5]
Alpha problems for cactus?

Examples:
https://i.imgur.com/XZwTgNq.png AD Reforged
https://i.imgur.com/fEgn0JF.png JSTR_Universal_17x
https://i.imgur.com/44wjdmA.png Faithful 64x
https://i.imgur.com/lMAHkt3.png icon example, faithful 64x

And transperent? Guess what, it is your converted PixelPerfection, looks like this: 
https://i.imgur.com/DzgDMLk.png :)

**Comment by sofar** [comment]
84bc2a8a035e918d2fe54219b5f87c18bc67bb0c
